"""init

Revision ID: 3f3f014f9299
Revises:
Create Date: 2026-03-16 18:59:30.285063

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3f3f014f9299'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS tripmark')
    op.execute('CREATE extension IF NOT EXISTS "uuid-ossp"')
    op.create_table(
        'countries',
        sa.Column('iso_a2', sa.String(length=2), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('iso_a2'),
        schema='tripmark',
    )
    op.create_table(
        'telegram_users',
        sa.Column('telegram_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=32), nullable=True),
        sa.Column('first_name', sa.String(length=64), nullable=True),
        sa.Column('last_name', sa.String(length=64), nullable=True),
        sa.Column('photo_url', sa.String(length=128), nullable=True),
        sa.Column('language_code', sa.String(length=10), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('telegram_id'),
        sa.UniqueConstraint('telegram_id'),
        schema='tripmark',
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=True),
        sa.Column('password_hash', sa.String(length=64), nullable=True),
        sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['telegram_user_id'], ['tripmark.telegram_users.telegram_id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        schema='tripmark',
    )
    op.create_index(
        'idx_unique_email',
        'users',
        ['email'],
        unique=True,
        schema='tripmark',
        postgresql_where=sa.text('email IS NOT NULL'),
    )
    op.create_table(
        'visits',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('country_code', sa.String(length=2), nullable=False),
        sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('trip_date', sa.Date(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['country_code'], ['tripmark.countries.iso_a2'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['tripmark.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='tripmark',
    )
    op.create_index('idx_country_code', 'visits', ['country_code'], unique=False, schema='tripmark')
    op.create_index('idx_user_id', 'visits', ['user_id'], unique=False, schema='tripmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='visits', schema='tripmark')
    op.drop_index('idx_country_code', table_name='visits', schema='tripmark')
    op.drop_table('visits', schema='tripmark')
    op.drop_index(
        'idx_unique_email', table_name='users', schema='tripmark', postgresql_where=sa.text('email IS NOT NULL')
    )
    op.drop_table('users', schema='tripmark')
    op.drop_table('telegram_users', schema='tripmark')
    op.drop_table('countries', schema='tripmark')
    # ### end Alembic commands ###
