"""added telegram_id

Revision ID: 48609da9434c
Revises: 20260308_0001
Create Date: 2026-03-15 13:46:32.149128

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48609da9434c'
down_revision = '20260308_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(length=320), nullable=True)
    op.alter_column('users', 'password_hash', existing_type=sa.VARCHAR(length=64), nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('idx_unique_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_visits_country_code'), table_name='visits')
    op.drop_index(op.f('ix_visits_user_id'), table_name='visits')
    op.create_index('idx_country_code', 'visits', ['country_code'], unique=False)
    op.create_index('idx_user_id', 'visits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='visits')
    op.drop_index('idx_country_code', table_name='visits')
    op.create_index(op.f('ix_visits_user_id'), 'visits', ['user_id'], unique=False)
    op.create_index(op.f('ix_visits_country_code'), 'visits', ['country_code'], unique=False)
    op.drop_index('idx_unique_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash', existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(length=320), nullable=False)
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
