"""added travels

Revision ID: 97416cb5e0b2
Revises: dc75048e7837
Create Date: 2026-04-21 15:31:55.916023

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97416cb5e0b2'
down_revision = 'dc75048e7837'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'visits_cities',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('visit_id', sa.Uuid(), nullable=False),
        sa.Column('city_id', sa.Uuid(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['city_id'], ['tripmark.cities.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['visit_id'], ['tripmark.visits.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='tripmark',
    )
    op.create_index('idx_visits_cities_city_id', 'visits_cities', ['city_id'], unique=False, schema='tripmark')
    op.create_index(
        'idx_visits_cities_visit_city_unique', 'visits_cities', ['visit_id', 'city_id'], unique=True, schema='tripmark'
    )
    op.create_index('idx_visits_cities_visit_id', 'visits_cities', ['visit_id'], unique=False, schema='tripmark')
    op.add_column(
        'files',
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        schema='tripmark',
    )
    op.add_column(
        'files',
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        schema='tripmark',
    )
    op.add_column(
        'files_visits', sa.Column('is_cover', sa.Boolean(), server_default='false', nullable=False), schema='tripmark'
    )
    op.add_column(
        'files_visits',
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        schema='tripmark',
    )
    op.add_column(
        'files_visits',
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        schema='tripmark',
    )
    op.add_column('files_visits', sa.Column('visibility', sa.String(length=16), nullable=False), schema='tripmark')
    op.create_index(
        'idx_files_visits_cover_unique',
        'files_visits',
        ['visit_id'],
        unique=True,
        schema='tripmark',
        postgresql_where=sa.text('is_cover IS true AND visit_id IS NOT NULL'),
    )
    op.create_index('idx_files_visits_is_cover', 'files_visits', ['is_cover'], unique=False, schema='tripmark')
    op.add_column(
        'otp_requests',
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        schema='tripmark',
    )
    op.create_unique_constraint(None, 'telegram_users', ['telegram_id'], schema='tripmark')
    op.add_column('visits', sa.Column('title', sa.String(length=80), nullable=True), schema='tripmark')
    op.add_column('visits', sa.Column('description', sa.Text(), nullable=True), schema='tripmark')
    op.add_column(
        'visits', sa.Column('visibility', sa.String(length=16), server_default=sa.text('private')), schema='tripmark'
    )
    op.add_column(
        'visits',
        sa.Column('date_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
        schema='tripmark',
    )
    op.add_column('visits', sa.Column('date_to', sa.Date(), nullable=True), schema='tripmark')
    op.create_index('idx_visits_visibility', 'visits', ['visibility'], unique=False, schema='tripmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visits_visibility', table_name='visits', schema='tripmark')
    op.drop_column('visits', 'date_to', schema='tripmark')
    op.drop_column('visits', 'date_from', schema='tripmark')
    op.drop_column('visits', 'visibility', schema='tripmark')
    op.drop_column('visits', 'description', schema='tripmark')
    op.drop_column('visits', 'title', schema='tripmark')
    op.drop_constraint(None, 'telegram_users', schema='tripmark', type_='unique')
    op.drop_column('otp_requests', 'updated', schema='tripmark')
    op.drop_index('idx_files_visits_is_cover', table_name='files_visits', schema='tripmark')
    op.drop_index(
        'idx_files_visits_cover_unique',
        table_name='files_visits',
        schema='tripmark',
        postgresql_where=sa.text('is_cover IS true AND visit_id IS NOT NULL'),
    )
    op.drop_column('files_visits', 'visibility', schema='tripmark')
    op.drop_column('files_visits', 'updated', schema='tripmark')
    op.drop_column('files_visits', 'created', schema='tripmark')
    op.drop_column('files_visits', 'is_cover', schema='tripmark')
    op.drop_column('files', 'updated', schema='tripmark')
    op.drop_column('files', 'created', schema='tripmark')
    op.drop_index('idx_visits_cities_visit_id', table_name='visits_cities', schema='tripmark')
    op.drop_index('idx_visits_cities_visit_city_unique', table_name='visits_cities', schema='tripmark')
    op.drop_index('idx_visits_cities_city_id', table_name='visits_cities', schema='tripmark')
    op.drop_table('visits_cities', schema='tripmark')
    # ### end Alembic commands ###
