"""added capacity for code

Revision ID: cc6e41b32c8b
Revises: a8f2c1d3e7b9
Create Date: 2026-03-22 14:14:28.516022

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6e41b32c8b'
down_revision = 'a8f2c1d3e7b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_requests', sa.Column('code_hash', sa.String(length=64), nullable=False), schema='tripmark')
    op.add_column('otp_requests', sa.Column('status', sa.String(length=20), nullable=False), schema='tripmark')
    op.drop_column('otp_requests', 'code', schema='tripmark')
    op.create_unique_constraint('telegram_users_telegram_id_key', 'telegram_users', ['telegram_id'], schema='tripmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telegram_users_telegram_id_key', 'telegram_users', schema='tripmark', type_='unique')
    op.add_column(
        'otp_requests', sa.Column('code', sa.VARCHAR(length=16), autoincrement=False, nullable=False), schema='tripmark'
    )
    op.drop_column('otp_requests', 'code_hash', schema='tripmark')
    op.drop_column('otp_requests', 'status', schema='tripmark')
    # ### end Alembic commands ###
