"""added checklist, status, places

Revision ID: d5680011ca31
Revises: 97416cb5e0b2
Create Date: 2026-04-23 17:15:34.085848

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd5680011ca31'
down_revision = '97416cb5e0b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'visits_checklist',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('visit_id', sa.Uuid(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=16), server_default='to_do', nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['tripmark.users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['visit_id'], ['tripmark.visits.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='tripmark',
    )
    op.create_index('idx_visits_checklist_visit_id', 'visits_checklist', ['visit_id'], unique=False, schema='tripmark')
    op.create_table(
        'visits_places',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('visit_id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('is_visited', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['tripmark.users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['visit_id'], ['tripmark.visits.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='tripmark',
    )
    op.create_index('idx_visits_places_visit_id', 'visits_places', ['visit_id'], unique=False, schema='tripmark')
    op.create_index(
        'idx_visits_places_visit_title_unique',
        'visits_places',
        ['visit_id', 'title'],
        unique=True,
        schema='tripmark',
    )
    op.create_table(
        'visits_places_files',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('visit_place_id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['tripmark.files.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['visit_place_id'], ['tripmark.visits_places.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='tripmark',
    )
    op.create_index(
        'idx_visits_places_files_file_id', 'visits_places_files', ['file_id'], unique=False, schema='tripmark'
    )
    op.create_index(
        'idx_visits_places_files_visit_place_file_unique',
        'visits_places_files',
        ['visit_place_id', 'file_id'],
        unique=True,
        schema='tripmark',
    )
    op.create_index(
        'idx_visits_places_files_visit_place_id',
        'visits_places_files',
        ['visit_place_id'],
        unique=False,
        schema='tripmark',
    )
    op.add_column('visits', sa.Column('trip_start', sa.Date(), nullable=True), schema='tripmark')
    op.add_column('visits', sa.Column('trip_end', sa.Date(), nullable=True), schema='tripmark')
    op.add_column(
        'visits',
        sa.Column('status', sa.String(length=16), server_default='visited', nullable=False),
        schema='tripmark',
    )
    op.drop_column('visits', 'trip_date', schema='tripmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('trip_date', sa.DATE(), autoincrement=False, nullable=True), schema='tripmark')
    op.drop_column('visits', 'status', schema='tripmark')
    op.drop_column('visits', 'trip_end', schema='tripmark')
    op.drop_column('visits', 'trip_start', schema='tripmark')
    op.drop_constraint(None, 'telegram_users', schema='tripmark', type_='unique')
    op.drop_index('idx_visits_places_files_visit_place_id', table_name='visits_places_files', schema='tripmark')
    op.drop_index(
        'idx_visits_places_files_visit_place_file_unique', table_name='visits_places_files', schema='tripmark'
    )
    op.drop_index('idx_visits_places_files_file_id', table_name='visits_places_files', schema='tripmark')
    op.drop_table('visits_places_files', schema='tripmark')
    op.drop_index('idx_visits_places_visit_title_unique', table_name='visits_places', schema='tripmark')
    op.drop_index('idx_visits_places_visit_id', table_name='visits_places', schema='tripmark')
    op.drop_table('visits_places', schema='tripmark')
    op.drop_index('idx_visits_checklist_visit_id', table_name='visits_checklist', schema='tripmark')
    op.drop_table('visits_checklist', schema='tripmark')
    # ### end Alembic commands ###
