from web.api.achievements.schemas import *  # noqa: F403
from web.api.auth.schemas import *  # noqa: F403
from web.api.client_geo.schemas import *  # noqa: F403
from web.api.countries.schemas import *  # noqa: F403
from web.api.files.schemas import *  # noqa: F403
from web.api.followers.schemas import *  # noqa: F403
from web.api.healthcheck.schemas import *  # noqa: F403
from web.api.supports.schemas import *  # noqa: F403
from web.api.users.schemas import *  # noqa: F403
from web.api.visits.schemas import *  # noqa: F403
from web.api.visits_checklist.schemas import *  # noqa: F403
from web.api.visits_places.schemas import *  # noqa: F403
from web.api.visits_places_files.schemas import *  # noqa: F403
