from app.models.tables import (
    achievements,
    cities,
    countries,
    files,
    files_visits,
    followers,
    metadata,
    otp_requests,
    telegram_users,
    users,
    users_achievements,
    visits,
    visits_cities,
)

__all__ = [
    'metadata',
    'users',
    'countries',
    'cities',
    'visits',
    'visits_cities',
    'followers',
    'files',
    'files_visits',
    'achievements',
    'users_achievements',
    'telegram_users',
    'otp_requests',
]
