from web.api import (
    achievements_router,
    auth_router,
    client_geo_router,
    countries_router,
    files_router,
    followers_router,
    healthcheck_router,
    supports_router,
    users_router,
    visits_checklist_router,
    visits_places_files_router,
    visits_places_router,
    visits_router,
)

route_handlers = [
    auth_router,
    achievements_router,
    client_geo_router,
    countries_router,
    users_router,
    followers_router,
    files_router,
    visits_router,
    visits_checklist_router,
    visits_places_router,
    visits_places_files_router,
    healthcheck_router,
    supports_router,
]
